apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: pw-kafka-test
spec:
  template:
    spec:
      nodeSelector:
        role: infra            # same network as Kafka
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka at kafka-svc:29092..."
              until nc -z kafka-svc 29092; do
                echo "  kafka not ready, retrying in 3s"
                sleep 3
              done
              echo "Kafka is reachable"
      containers:
        - name: kafka-init
          image: confluentinc/cp-kafka:7.6.0
          command:
            - bash
            - -c
            - |
              kafka-topics --bootstrap-server kafka-svc:29092 --create --if-not-exists --topic orders            --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka-svc:29092 --create --if-not-exists --topic payments          --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka-svc:29092 --create --if-not-exists --topic notifications     --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka-svc:29092 --create --if-not-exists --topic dead-letter-queue --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka-svc:29092 --create --if-not-exists --topic audit-events      --partitions 3 --replication-factor 1
              echo "All 5 topics created successfully"
              kafka-topics --bootstrap-server kafka-svc:29092 --list
      restartPolicy: OnFailure
  backoffLimit: 5
